### ISSUE TITLE
Android QR config

### ISSUE THREAD

**Issue by squromiv** [b-m-f/WirtBot#196] opened 2021-04-14 12:21 UTC
WIrtbot v.2.6.7
Added new android device -> QR generated -> Native wireguard android client error "Unable to import, unknown section in config".

**Comment by b-m-f** [comment] 2021-04-14 12:27
Hey @squromiv,

thanks for all the tests!

I will check this out asap

**Comment by squromiv** [comment] 2021-04-21 13:27
Is there any updates?

**Comment by b-m-f** [comment] 2021-04-21 16:47
Hi @squromiv ,

I'm quite busy at the moment.

I hope I'll be able to push a fix by Monday!
Will ping you here.

**Comment by b-m-f** [comment] 2021-04-25 14:35
Hey @squromiv.

I just tried to reproduce this, but  could not get my phone to report any errors.

Is there any more output from the WireGuard App?

Which versions are you using?

Also could you provide some infos on the config for that device?

**Comment by squromiv** [comment] 2021-04-25 14:54
![Screenshot_20210425-175208_WireGuard](https://user-images.githubusercontent.com/15985877/115998295-49de3c00-a5ef-11eb-8af7-48b717c1b1ad.jpg)

**Comment by squromiv** [comment] 2021-04-25 14:56
Wirtbot v2.6.7.
With previous version application worked correctly.

**Comment by squromiv** [comment] 2021-04-25 15:26
I downloaded config manually and compare with old config files. The only difference that I see: is "space" character after comma in string
`AllowedIPs = 0.0.0.0/0, ::/0`
I don`t know whether it is important or not for generating QR.

**Comment by b-m-f** [comment] 2021-04-25 16:40
Nice catch. 
I will push a version without the space. Let's see if it helps!

**Comment by b-m-f** [comment] 2021-04-25 16:43
Ok weird.

There is no space when I am creating the configs. Everything imports fine, even with routed enabled.

Maybe there is a problem with old configs of yours?

Can you try to remove the device and readd it?

**Comment by squromiv** [comment] 2021-04-25 17:14
> Everything imports fine, even with routed enabled.
When I download config manually, it is imported into Android app correctly. But if I try to catch the same config by QR, mentioned error appears.

**Comment by squromiv** [comment] 2021-04-25 17:26
> I will push a version without the space. Let's see if it helps!

Current version is without the space. So let`s add it and try.

**Comment by b-m-f** [comment] 2021-04-26 19:43
Did it work for you?

**Comment by squromiv** [comment] 2021-04-26 19:45
> Did it work for you?

I don`t know how to build docker image. So I am still waiting your fix in order to try it. :-D

**Comment by b-m-f** [comment] 2021-04-26 20:35
So is 2.6.7 not the latest one that you can pull?

**Comment by squromiv** [comment] 2021-04-26 20:46
I am testing docker container with v.2.6.7 exactly.
![screen_2021 04 26](https://user-images.githubusercontent.com/15985877/116147751-c30d8a00-a6e8-11eb-852e-769b689ff140.png)
So in this case there is no "space" character. And Android app fails. Try to add it and I will check.

**Comment by b-m-f** [comment] 2021-04-27 08:03
Strange. As this works fine for me. 

Could you send me the QR code for testing to `max` AT `ehlers.berlin` ?

**Comment by squromiv** [comment] 2021-04-28 06:56
Have you received my email?

**Comment by b-m-f** [comment] 2021-04-28 07:01
@squromiv yup, will test this on a free day :)

**Comment by b-m-f** [comment] 2021-04-28 16:38
@squromiv I am getting a similar error with your QR code.

I assume this is due to the stretched picture. Can you try to open the QR code or download it and try again?

In that case the **CSS** needs to be fixed to ensure that it is always displayed correctly

**Comment by squromiv** [comment] 2021-04-29 08:36
It makes me crazy. Recreated WirBot container many times, checked in different browsers, cleaned cache, rebooted system, etc. And had the same result: QR recognition failed. But now generated pictures looks different: stretched in Google Chrome v. 75.0.3770.90 and "squared" in Firefox 88.0. So squared picture is imported successfully.

**Comment by b-m-f** [comment] 2021-04-29 10:08
Okay. What a strange edge case.

Thanks for all your effort!

Browsers really are a beast to work with correctly.

I will take some time tonight to get this fixed in Chrome and add a test case to make sure it stays correct in future versions.

**Comment by squromiv** [comment] 2021-04-29 10:29
Really strange. )))) When move window splitter (divides Wirbot and developer`s console page), sizes of the picture change.
![vid1](https://user-images.githubusercontent.com/15985877/116537473-f588d400-a8ee-11eb-8144-ea79793d2ea0.gif)

**Comment by b-m-f** [comment] 2021-04-29 17:54
v2.6.8 should fix this.

Should be in the docker registry in a few hours. GihubCI takes quite a while to build for multiple CPU architectures

**Comment by b-m-f** [comment] 2021-04-29 20:31
Something is wrong with the Github CI. I will revisit this tomorrow

**Comment by b-m-f** [comment] 2021-05-01 21:12
Hi,

managed to manually push the latest version.

Can you try 2.6.8?

**Comment by squromiv** [comment] 2021-05-03 09:29
> Can you try 2.6.8?

I have tried build 2.6.9. QR-generator looks as fixed. Thank you.

**Closed** 2021-05-03 09:29 UTC
