### ISSUE TITLE
Import  ImportThisFileIntoYourWirtBotInterface.json does not do anything 

### ISSUE THREAD

**Issue by agalewsky-pnn** [b-m-f/WirtBot#108] opened 2020-10-19 19:38 UTC
I have successfully install wirtbot and have connected to the dashboard. However, when I try to import  ImportThisFileIntoYourWirtBotInterface.json as a backup and click the import button - nothing happens.  I can't find any errors thrown.  I have tried Chrome, Firefox and Safari and they all yield the same results.

Any thoughts?

-Andy

**Comment by b-m-f** [comment] 2020-10-20 13:30
Hi @agalewsky-pnn / Andy,

Nothing shows up after a refresh either?

Could you paste the output of `ImportThisFileIntoYourWirtBotInterface.json` ?

Just make sure to remove the Keys from the output :)

**Comment by b-m-f** [comment] 2020-10-20 14:19
So, I just set up a new WirtBot again and could not reproduce this. 

Importing worked without any issues. Are you trying to import on `wirtbot.wirt.internal`?

**Comment by agalewsky-pnn** [comment] 2020-10-21 00:43
Let me try again.  Is it important to do it from that address?

**Comment by b-m-f** [comment] 2020-10-21 06:05
Hm, the address should not matter too much.
I am just curious how else you would reach the DashBoard?

**Comment by agalewsky-pnn** [comment] 2020-10-21 14:24
I used the IP address, but I think I also tried the DNS name as well.   One
thing I am going to check if I have any popup blockers, etc. engaged on my
browser(s)

**Comment by b-m-f** [comment] 2020-10-21 14:47
@agalewsky-pnn Make sure to access via the internal IP or the Hostname.

There was an uncommented line in the installer. This is fixed now.

Try `npm install -g @wirtbot/installer@1.0.8`. And use the update functionality to get the latest version

**Comment by agalewsky-pnn** [comment] 2020-10-25 00:15
I am getting this error in the browser console:
Uncaught SyntaxError: Unexpected token
 in JSON at position 175
    at JSON.parse (<anonymous>)
    at FileReader.t.onload (Settings.vue:93)

I am using the file generated by the application

-Andy

**Comment by b-m-f** [comment] 2020-10-25 07:39
Interesting. 

Could you post your JSON as well please?

Just remove the keys beforehand

**Comment by b-m-f** [comment] 2020-10-25 15:43
2 more things:

- Have you updated the latest `@wirtbot/installer`?
- Did you already use the `update` functionality of the installer?

**Comment by b-m-f** [comment] 2020-11-02 08:55
No more info given -> closed

**Closed by b-m-f** 2020-11-02 08:55 UTC
Labels: question
