### ISSUE TITLE
Config implementation

### ISSUE THREAD

**Issue by squromiv** [b-m-f/WirtBot#193] opened 2021-04-04 06:54 UTC
Set up wirtbot->added one client->made backup of dashboard->added a second client->cleaned cache of a browser->restored backup->message, that **config updated** successfully

![screen_2021 04 04 002](https://user-images.githubusercontent.com/15985877/113500880-3bd65780-952a-11eb-892c-c9e2c931006a.png)

So on the configuration page I see one device
![screen_2021 04 04 007](https://user-images.githubusercontent.com/15985877/113501629-5101b500-952f-11eb-9e25-aaa92d06d85a.png)

But in fact, there are two devices in server.conf file, placed in "/var/lib/docker/volumes/wirtbot_wireguard-data/_data". And they are both stay connected with the server.
![screen_2021 04 04](https://user-images.githubusercontent.com/15985877/113500960-b56e4580-952a-11eb-8fd6-f2d1cd9eea95.png)

Set up realization of Wirtbot looks unusable or I don`t understand anything.

**Comment by squromiv** [comment] 2021-04-04 07:10
Why don't you simply store and load options from server side to dashboard?
Please, take a look at [https://github.com/perara/wg-manager](wg-manager)
![screen_2021 04 04](https://user-images.githubusercontent.com/15985877/113501465-ebf98f80-952d-11eb-94b9-a5fac1966594.png)

**Comment by squromiv** [comment] 2021-04-04 07:17
Also, in my opinion, too much space takes one device config in Wirtbot. Think about doing it collapsed as it is done in wg-manager and similar software.

**Comment by b-m-f** [comment] 2021-04-04 07:28
Hi @squromiv 

So, for the first problem this should be a bug.

Will look into this.

# server side data
Design choices on the project architecture are deliberate and won't be challenged until they hit a real blocker.
Client side control makes management easier for me.

# UI change
As for the collapsing. Seems like a neat feature with low priority for me.
Might implement this at some point in the future.

**Comment by b-m-f** [comment] 2021-04-04 09:06
@squromiv 
There was indeed a bug in device deletion. 

Maybe that fixed the issue you saw, because I have created a test for your described scenario and was not able to reproduce.

The backups seem to correctly overwrite old configs. Atleast this is true for version **v2.6.6**. Releasing this today, so you might want to retry.

**Comment by b-m-f** [comment] 2021-04-10 16:06
@squromiv is backup working for you now?

If so I'd go ahead and close this

**Comment by squromiv** [comment] 2021-04-11 10:44
I will check today.

**Comment by squromiv** [comment] 2021-04-14 11:20
@b-m-f  Yes. Backup restore is now working, as well as "Delete" button. Let`s close this issue. Thanks.

**Closed** 2021-04-14 11:38 UTC
